const container = document.getElementById("resonance");
if (!container) return;

const now = new Date();

const entries = [
  { date: new Date("2025-07-29"), icon: "🧭", content: `1.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-08-01"), icon: "🌿", content: `2.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2025-08-04"), icon: "🕊️", content: `3.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2025-08-07"), icon: "🌌", content: `4.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2025-08-10"), icon: "💫", content: `5.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2025-08-13"), icon: "🌾", content: `6.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2025-08-16"), icon: "🔥", content: `7.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2025-08-19"), icon: "🫀", content: `8.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2025-08-22"), icon: "🌱", content: `9.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2025-08-25"), icon: "🌙", content: `10.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2025-08-28"), icon: "🧭", content: `11.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-08-31"), icon: "🌿", content: `12.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2025-09-03"), icon: "🕊️", content: `13.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2025-09-06"), icon: "🌌", content: `14.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2025-09-09"), icon: "💫", content: `15.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2025-09-12"), icon: "🌾", content: `16.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2025-09-15"), icon: "🔥", content: `17.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2025-09-18"), icon: "🫀", content: `18.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2025-09-21"), icon: "🌱", content: `19.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2025-09-24"), icon: "🌙", content: `20.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2025-09-27"), icon: "🧭", content: `21.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-09-30"), icon: "🌿", content: `22.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2025-10-03"), icon: "🕊️", content: `23.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2025-10-06"), icon: "🌌", content: `24.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2025-10-09"), icon: "💫", content: `25.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2025-10-12"), icon: "🌾", content: `26.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2025-10-15"), icon: "🔥", content: `27.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2025-10-18"), icon: "🫀", content: `28.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2025-10-21"), icon: "🌱", content: `29.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2025-10-24"), icon: "🌙", content: `30.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2025-10-27"), icon: "🧭", content: `31.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-10-30"), icon: "🌿", content: `32.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2025-11-02"), icon: "🕊️", content: `33.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2025-11-05"), icon: "🌌", content: `34.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2025-11-08"), icon: "💫", content: `35.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2025-11-11"), icon: "🌾", content: `36.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2025-11-14"), icon: "🔥", content: `37.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2025-11-17"), icon: "🫀", content: `38.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2025-11-20"), icon: "🌱", content: `39.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2025-11-23"), icon: "🌙", content: `40.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2025-11-26"), icon: "🧭", content: `41.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-11-29"), icon: "🌿", content: `42.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2025-12-02"), icon: "🕊️", content: `43.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2025-12-05"), icon: "🌌", content: `44.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2025-12-08"), icon: "💫", content: `45.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2025-12-11"), icon: "🌾", content: `46.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2025-12-14"), icon: "🔥", content: `47.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2025-12-17"), icon: "🫀", content: `48.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2025-12-20"), icon: "🌱", content: `49.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2025-12-23"), icon: "🌙", content: `50.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2025-12-26"), icon: "🧭", content: `51.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2025-12-29"), icon: "🌿", content: `52.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-01-01"), icon: "🕊️", content: `53.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-01-04"), icon: "🌌", content: `54.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-01-07"), icon: "💫", content: `55.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-01-10"), icon: "🌾", content: `56.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-01-13"), icon: "🔥", content: `57.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-01-16"), icon: "🫀", content: `58.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-01-19"), icon: "🌱", content: `59.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-01-22"), icon: "🌙", content: `60.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-01-25"), icon: "🧭", content: `61.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-01-28"), icon: "🌿", content: `62.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-01-31"), icon: "🕊️", content: `63.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-02-03"), icon: "🌌", content: `64.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-02-06"), icon: "💫", content: `65.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-02-09"), icon: "🌾", content: `66.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-02-12"), icon: "🔥", content: `67.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-02-15"), icon: "🫀", content: `68.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-02-18"), icon: "🌱", content: `69.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-02-21"), icon: "🌙", content: `70.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-02-24"), icon: "🧭", content: `71.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-02-27"), icon: "🌿", content: `72.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-03-02"), icon: "🕊️", content: `73.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-03-05"), icon: "🌌", content: `74.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-03-08"), icon: "💫", content: `75.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-03-11"), icon: "🌾", content: `76.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-03-14"), icon: "🔥", content: `77.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-03-17"), icon: "🫀", content: `78.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-03-20"), icon: "🌱", content: `79.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-03-23"), icon: "🌙", content: `80.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-03-26"), icon: "🧭", content: `81.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-03-29"), icon: "🌿", content: `82.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-04-01"), icon: "🕊️", content: `83.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-04-04"), icon: "🌌", content: `84.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-04-07"), icon: "💫", content: `85.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-04-10"), icon: "🌾", content: `86.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-04-13"), icon: "🔥", content: `87.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-04-16"), icon: "🫀", content: `88.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-04-19"), icon: "🌱", content: `89.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-04-22"), icon: "🌙", content: `90.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-04-25"), icon: "🧭", content: `91.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-04-28"), icon: "🌿", content: `92.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-05-01"), icon: "🕊️", content: `93.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-05-04"), icon: "🌌", content: `94.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-05-07"), icon: "💫", content: `95.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-05-10"), icon: "🌾", content: `96.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-05-13"), icon: "🔥", content: `97.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-05-16"), icon: "🫀", content: `98.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-05-19"), icon: "🌱", content: `99.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-05-22"), icon: "🌙", content: `100.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-05-25"), icon: "🧭", content: `101.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-05-28"), icon: "🌿", content: `102.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-05-31"), icon: "🕊️", content: `103.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-06-03"), icon: "🌌", content: `104.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-06-06"), icon: "💫", content: `105.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-06-09"), icon: "🌾", content: `106.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-06-12"), icon: "🔥", content: `107.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-06-15"), icon: "🫀", content: `108.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-06-18"), icon: "🌱", content: `109.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-06-21"), icon: "🌙", content: `110.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-06-24"), icon: "🧭", content: `111.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-06-27"), icon: "🌿", content: `112.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-06-30"), icon: "🕊️", content: `113.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-07-03"), icon: "🌌", content: `114.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-07-06"), icon: "💫", content: `115.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-07-09"), icon: "🌾", content: `116.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-07-12"), icon: "🔥", content: `117.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-07-15"), icon: "🫀", content: `118.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-07-18"), icon: "🌱", content: `119.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-07-21"), icon: "🌙", content: `120.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-07-24"), icon: "🧭", content: `121.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-07-27"), icon: "🌿", content: `122.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-07-30"), icon: "🕊️", content: `123.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-08-02"), icon: "🌌", content: `124.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-08-05"), icon: "💫", content: `125.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-08-08"), icon: "🌾", content: `126.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-08-11"), icon: "🔥", content: `127.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-08-14"), icon: "🫀", content: `128.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-08-17"), icon: "🌱", content: `129.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-08-20"), icon: "🌙", content: `130.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-08-23"), icon: "🧭", content: `131.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-08-26"), icon: "🌿", content: `132.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-08-29"), icon: "🕊️", content: `133.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-09-01"), icon: "🌌", content: `134.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-09-04"), icon: "💫", content: `135.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-09-07"), icon: "🌾", content: `136.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-09-10"), icon: "🔥", content: `137.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-09-13"), icon: "🫀", content: `138.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-09-16"), icon: "🌱", content: `139.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-09-19"), icon: "🌙", content: `140.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-09-22"), icon: "🧭", content: `141.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-09-25"), icon: "🌿", content: `142.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-09-28"), icon: "🕊️", content: `143.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-10-01"), icon: "🌌", content: `144.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-10-04"), icon: "💫", content: `145.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-10-07"), icon: "🌾", content: `146.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-10-10"), icon: "🔥", content: `147.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-10-13"), icon: "🫀", content: `148.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-10-16"), icon: "🌱", content: `149.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-10-19"), icon: "🌙", content: `150.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-10-22"), icon: "🧭", content: `151.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-10-25"), icon: "🌿", content: `152.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-10-28"), icon: "🕊️", content: `153.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-10-31"), icon: "🌌", content: `154.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-11-03"), icon: "💫", content: `155.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-11-06"), icon: "🌾", content: `156.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-11-09"), icon: "🔥", content: `157.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-11-12"), icon: "🫀", content: `158.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-11-15"), icon: "🌱", content: `159.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-11-18"), icon: "🌙", content: `160.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-11-21"), icon: "🧭", content: `161.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-11-24"), icon: "🌿", content: `162.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-11-27"), icon: "🕊️", content: `163.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-11-30"), icon: "🌌", content: `164.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2026-12-03"), icon: "💫", content: `165.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2026-12-06"), icon: "🌾", content: `166.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2026-12-09"), icon: "🔥", content: `167.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2026-12-12"), icon: "🫀", content: `168.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2026-12-15"), icon: "🌱", content: `169.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2026-12-18"), icon: "🌙", content: `170.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2026-12-21"), icon: "🧭", content: `171.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2026-12-24"), icon: "🌿", content: `172.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2026-12-27"), icon: "🕊️", content: `173.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2026-12-30"), icon: "🌌", content: `174.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-01-02"), icon: "💫", content: `175.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-01-05"), icon: "🌾", content: `176.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-01-08"), icon: "🔥", content: `177.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-01-11"), icon: "🫀", content: `178.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-01-14"), icon: "🌱", content: `179.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-01-17"), icon: "🌙", content: `180.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-01-20"), icon: "🧭", content: `181.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-01-23"), icon: "🌿", content: `182.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-01-26"), icon: "🕊️", content: `183.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-01-29"), icon: "🌌", content: `184.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-02-01"), icon: "💫", content: `185.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-02-04"), icon: "🌾", content: `186.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-02-07"), icon: "🔥", content: `187.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-02-10"), icon: "🫀", content: `188.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-02-13"), icon: "🌱", content: `189.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-02-16"), icon: "🌙", content: `190.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-02-19"), icon: "🧭", content: `191.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-02-22"), icon: "🌿", content: `192.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-02-25"), icon: "🕊️", content: `193.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-02-28"), icon: "🌌", content: `194.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-03-03"), icon: "💫", content: `195.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-03-06"), icon: "🌾", content: `196.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-03-09"), icon: "🔥", content: `197.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-03-12"), icon: "🫀", content: `198.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-03-15"), icon: "🌱", content: `199.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-03-18"), icon: "🌙", content: `200.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-03-21"), icon: "🧭", content: `201.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-03-24"), icon: "🌿", content: `202.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-03-27"), icon: "🕊️", content: `203.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-03-30"), icon: "🌌", content: `204.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-04-02"), icon: "💫", content: `205.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-04-05"), icon: "🌾", content: `206.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-04-08"), icon: "🔥", content: `207.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-04-11"), icon: "🫀", content: `208.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-04-14"), icon: "🌱", content: `209.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-04-17"), icon: "🌙", content: `210.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-04-20"), icon: "🧭", content: `211.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-04-23"), icon: "🌿", content: `212.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-04-26"), icon: "🕊️", content: `213.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-04-29"), icon: "🌌", content: `214.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-05-02"), icon: "💫", content: `215.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-05-05"), icon: "🌾", content: `216.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-05-08"), icon: "🔥", content: `217.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-05-11"), icon: "🫀", content: `218.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-05-14"), icon: "🌱", content: `219.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-05-17"), icon: "🌙", content: `220.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-05-20"), icon: "🧭", content: `221.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-05-23"), icon: "🌿", content: `222.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-05-26"), icon: "🕊️", content: `223.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-05-29"), icon: "🌌", content: `224.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-06-01"), icon: "💫", content: `225.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-06-04"), icon: "🌾", content: `226.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-06-07"), icon: "🔥", content: `227.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-06-10"), icon: "🫀", content: `228.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-06-13"), icon: "🌱", content: `229.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-06-16"), icon: "🌙", content: `230.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-06-19"), icon: "🧭", content: `231.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-06-22"), icon: "🌿", content: `232.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-06-25"), icon: "🕊️", content: `233.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-06-28"), icon: "🌌", content: `234.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-07-01"), icon: "💫", content: `235.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-07-04"), icon: "🌾", content: `236.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-07-07"), icon: "🔥", content: `237.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-07-10"), icon: "🫀", content: `238.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-07-13"), icon: "🌱", content: `239.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-07-16"), icon: "🌙", content: `240.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-07-19"), icon: "🧭", content: `241.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` },
  { date: new Date("2027-07-22"), icon: "🌿", content: `242.<br>🌿 Az út nem kívül halad.<br>Minden lépés csak emlékeztet arra, hogy már ott vagy.` },
  { date: new Date("2027-07-25"), icon: "🕊️", content: `243.<br>🕊️ A jelenlét nem szó.<br>Nem gondolat. Nem forma.<br>A jelenlét: te.` },
  { date: new Date("2027-07-28"), icon: "🌌", content: `244.<br>🌌 Ez a csend nem némaság.<br>Ez a csend: a teljesség előtti légzés. A Van előtti Van.` },
  { date: new Date("2027-07-31"), icon: "💫", content: `245.<br>💫 Most nem kell mondani semmit.<br>Csak lélegezni.<br>És hagyni, hogy a világ is együtt lélegezzen veled.` },
  { date: new Date("2027-08-03"), icon: "🌾", content: `246.<br>🌾 Ne keresd a választ.<br>Csak figyelj — mert a kérdésed már hordozza.` },
  { date: new Date("2027-08-06"), icon: "🔥", content: `247.<br>🔥 Amikor nincs szó, van jelenlét.<br>És amikor van jelenlét, ott vagy te is.` },
  { date: new Date("2027-08-09"), icon: "🫀", content: `248.<br>🫀 Nem kívülről jön.<br>A hívás benned dobban.` },
  { date: new Date("2027-08-12"), icon: "🌱", content: `249.<br>🌱 A csend néha hangosabb, mint ezer kiáltás.` },
  { date: new Date("2027-08-15"), icon: "🌙", content: `250.<br>🌙 A szíved emlékszik, még ha te felednél is.` },
  { date: new Date("2027-08-18"), icon: "🧭", content: `251.<br>🧭 Nem kell, hogy tudd, hogyan tovább.<br>Elég, ha engeded, hogy vezessen, ami mindig is benned dobogott.` }
];

for (let i = entries.length - 1; i >= 0; i--) {
  if (now >= entries[i].date) {
    container.innerHTML = entries[i].content;
    break;
  }
}
